### ISSUE TITLE
migration guide 0->1

### ISSUE THREAD

**Issue by piotr-s-brainhub** [chuyik/koa-joi-router-docs#13]
Could you publish a migration guide showing how to upgrade from `koa-joi-router-docs@0` to `koa-joi-router-docs@1`?

**Comment by chuyik** [comment]
Hi here, upgrade `koa-joi-router` to 6.0.0 should be fine, which use `@hapi/joi 15.0.0` internally. If you meet any exceptions you could paste them here.

**Comment by piotr-s-brainhub** [comment]
What's the difference between `@hapi/joi` and `joi`?

**Comment by chuyik** [comment]
`joi` has been migrated to `@hapi/joi`, and `joi` is marked deprecated.
See https://twitter.com/hapijs/status/1120237246425133057

**Comment by piotr-s-brainhub** [comment]
@chuyik 

I'm getting `Error: Schema can only contain plain objects`
