### ISSUE TITLE
Output Description is Always Success

### ISSUE THREAD

**Issue by ahoopes16** [chuyik/koa-joi-router-docs#14]
I'm trying to show output response examples, but the responses still show a description of "Success" even when the status code is, say, 500. It should say "Failure".

Is there somewhere in the route definitions that I can specify what it should say instead? I tried specifying it in the `defaultResponses` but it didn't seem to change anything. I feel like there must be something I'm missing.

**Comment by chuyik** [comment]
Thanks for pointing this out, with version `1.0.1`, you could set `description` like this:
```js
output: {
  500: {
    body: Joi.object({
      message: Joi.string()
    }).description('here you can say `Failure`')
  }
}
```

And I just release `1.0.2`, with which you could config `defaultResponses` like this:
```js
defaultResponses: {
  200: {
    description: 'OK'
  },
  500: {
    description: 'Failure'
  }
}
```

**Comment by ahoopes16** [comment]
Ah fantastic, thanks so much for the information. Appreciate it!
