### ISSUE TITLE
展示接口的页面没有渲染 joi.example() 里面的示例数据

### ISSUE THREAD

**Issue by Tseian** [chuyik/koa-joi-router-docs#8]
展示接口的页面没有渲染 joi.example() 里面的示例数据，只展示default的数据。

**Comment by chuyik** [comment]
Sorry we haven't implemented all Joi apis yet, but you are welcome to contribute if you have interest!

**Comment by Tseian** [comment]
ok, I'll try. thank you.

**Comment by cbarrese** [comment]
I'd be interested in making a contribution for this.  It looks like I would have to change a dependent project [o2team-joi-to-swagger](https://github.com/chuyik/joi-to-swagger), which is forked from https://github.com/Twipped/joi-to-swagger.  There is already an open issue on https://github.com/Twipped/joi-to-swagger/issues/34 to implement this feature.  If I offer to make a contribution there would you merge into the projects you have forked, or would you rather have a Pull Request against [o2team-joi-to-swagger](https://github.com/chuyik/joi-to-swagger)?

Really like the lib you've created here 👍

**Comment by chuyik** [comment]
@cbarrese Hey thanks for your appreciation. Either way is fine, but I would prefer the former that you could send a PR to `Twipped/joi-to-swagger` and then I merge it.

**Comment by Tseian** [comment]
@chuyik Hi, I have send a PR for this issue, please review the [code](https://github.com/chuyik/joi-to-swagger/pull/3/commits/49d2c453fc7da340c89681571fcf805c757d7b60),.
